### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by alexandear** [manuelarte/funcorder#11]
I'm a contributor to [golangci-lint](https://github.com/golangci/golangci-lint/pull/5630) and an experienced Go developer. I'd like to propose several improvements to this linter:
 
1. Fix typos.

```txt
./CHANGELOG.md:13: delcaration ==> declaration
./README.md:77: Consturctor ==> Constructor
./internal/utils/utils.go:15: Prefixs ==> Prefixes
```

Tools like https://github.com/codespell-project/codespell, https://github.com/crate-ci/typos can help detect misspellings.

2. Add the ability to disable specific suggestions via settings. For example, if someone wants to enable the "unexported method" check but not the "constructor should be placed before struct method" check, they currently can't.

3. Use the latest Go version for testing to catch issues early, such as gostaticanalysis/forcetypeassert#19.
```yaml
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
```

You can use a `matrix` strategy to test against the two latest Go versions, as you did for the `golangci` job.

4. Refactor package structure:

- The `utils` package is uncommon in Go projects.  As noted in the [CodeReviewComments](https://go.dev/wiki/CodeReviewComments#package-names), avoid meaningless package names like util, common, misc, api, types, and interfaces.
- `pkg/analyzer` can be simply `analyzer`.

5. Enable `gofmt` formatter to rewrite `interface{}` to `any`:
```yaml
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
```

6. Improve linter's `Doc` field. Update `checks function order` to `checks the order of functions, methods, and constructors` for clarity.
7. Fix TOC items in README:

E.g.,
```md
[Check exported methods are placed before not exported methods](#check-exported-methods-are-placed-before-not-exported-methods)
```
should be
```md
[Check exported methods are placed before non-exported methods](#check-exported-methods-are-placed-before-non-exported-methods)
```

Would love to hear your thoughts on these suggestions! 🚀
