### ISSUE TITLE
feature request: func order method-sections

### ISSUE THREAD

**Issue by sonatard** [manuelarte/funcorder#27]
Make it possible to specify the order of methods in the config.

exported-methods and unexported-methods are all methods that do not match other sections.

```yaml
    funcorder:
      method-sections:
        - exported-method
        - unexported-method
        - Update.*
        - update.*
        - Delete.*
        - delete.*
```

This config is based on gci.

It might be better to include functions as well, rather than limiting it to methods.
